# Generated by Django 5.1.1 on 2024-09-24 18:44

import django.db.models.deletion
import mailing.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mailing.utils.upload_to,
                        verbose_name="аватар",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="тема письма")),
                ("body", models.TextField(verbose_name="текст письма")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания рассылки"
                    ),
                ),
                (
                    "first_send_time",
                    models.DateTimeField(
                        verbose_name="дата и время первой отправки рассылки"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("D", "Раз в день"),
                            ("W", "Раз в неделю"),
                            ("M", "Раз в месяц"),
                        ],
                        default="W",
                        max_length=1,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CR", "Создана"),
                            ("RN", "Запущена"),
                            ("CO", "Завершена"),
                        ],
                        default="CR",
                        max_length=2,
                        verbose_name="статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="distributions",
                        to="mailing.client",
                        verbose_name="клиенты",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mailings",
                        to="mailing.message",
                        verbose_name="сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DistributionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время послежней попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "Успешно"), ("F", "Неуспешно")],
                        default="F",
                        max_length=1,
                        verbose_name="статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Ответ почтового сервера, если он был.",
                        null=True,
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.distribution",
                        verbose_name="рассылка",
                    ),
                ),
            ],
        ),
    ]
