# Generated by Django 5.1.1 on 2024-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_rename_distribution_mailing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="clients", to="mailing.client", verbose_name="клиенты"
            ),
        ),
    ]
