# Generated by Django 5.1.1 on 2024-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_clients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="distribution",
            new_name="mailing",
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата и время попытки отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="ответ почтового сервера"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SC", "Успешно"), ("FL", "Неуспешно")],
                max_length=2,
                verbose_name="статус попытки",
            ),
        ),
    ]
