# Generated by Django 5.1.1 on 2024-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активность рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("CR", "Создана"), ("RN", "Запущена")],
                default="CR",
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
