# Generated by Django 5.1.1 on 2024-09-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailing_is_active_alter_mailing_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="first_send_time",
            new_name="send_time",
        ),
    ]
